config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only:[:new, :create, :update, :edit]
  # get("users/:id/edit", {to: 'users#edit', as: 'edit_user'})
  get("users/:id/edit/pass_edit", {to: 'users#pass_edit', as: 'edit_user_password'})
  post("users/:id/edit/pass_edit/pass_update", {to: 'users#pass_update',as: 'create_user_password'})
  resource :session, only:[:new, :create, :destroy]

  resources :posts, except: [:index] do
    resources :comments, only: [:create, :destroy]
  end

  get("/", { to: 'posts#index', as: 'root' })
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      # if user.admin?
      #   can :manage, :all
      # else
      #   can :read, :all
      # end
    
      alias_action :create, :read, :edit, :update, :destroy, :delete, to: :crud

      can(:crud, Post) do |post|
        post.user == user
      end

      can(:crud, Comment) do |com|
        com.user == user || com.post.user == user
      end
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    

    validates(:title, presence: true, uniqueness: true)
    validates(:body, presence:true, length: {minimum: 50})
end

app/models/user.rb
class User < ApplicationRecord
has_many :posts, dependent: :nullify
has_many :comments, dependent: :nullify

has_secure_password
    validates(:name, presence: true)
    validates(:password, presence: true)
    validates(:email, presence: true, uniqueness: true, format: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    private 

    def current_user
        if session[:user_id].present?
            @current_user ||= User.find_by(id: session[:user_id])
        end
    end
    helper_method :current_user

    def authenticate_user!
        unless current_user.present?
            flash[:alert] = "You must sign in or sign up first!"
            redirect_to root_path
        end
    end
    helper_method :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

    def create
        @post = Post.find(params[:post_id])
        @comment = Comment.new comment_params
        @comment.post = @post
        @comment.user = current_user
        if @comment.save
            redirect_to post_path(@post)
          else
            @posts = @post.comments.order(created_at: :desc)
            render 'posts/show'
          end

    end

    def destroy
        @comment = Comment.find(params[:id])
        if can?(:crud, @comment)
          @comment.destroy
        redirect_to post_path(@comment.post)
        else
        # head will send an empty HTTP response with a particular reponse code
        # in this case :unauthorized code is 401
        # http://billpatrianakos.me/blog/2013/10/13/list-of-rails-status-code-symbols/
          head:unauthorized
        end
    end


    private
  
    def comment_params
      params.require(:comment).permit(:body)
    end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :find_post, only: [:show, :edit, :update, :destroy]
    before_action :authorize, only: [:edit, :update, :destroy]
    
    def index
        @posts = Post.all.order(created_at: :desc)
    end

    def show
        @comment= Comment.new
        @comments = @post.comments.order(created_at: :desc)
    end

    def new
        @post = Post.new
    end
    def create
        @post = Post.new post_params
        @post.user = current_user
        if @post.save
            redirect_to root_path
        else
            render :new
        end
    end

    def destroy
        @post.destroy
        redirect_to root_path
    end

    def edit
    #   if !can? :crud, @question
    #     redirect_to root_path, alert: 'Not authorized'
    #   end
    end

    def update
        if @post.update post_params
            redirect_to post_path(@post.id)
        else
            render :edit
        end
    end

    private
  
    def post_params
      params.require(:post).permit(:title, :body)
    end
  
    def find_post
      @post = Post.find(params[:id])
    end

    def authorize
        unless can?(:crud, @post) 
        redirect_to root_path, alert: 'Not Authorized'
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
     user = User.find_by_email(params[:email])
     if user&.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to root_path, notice: 'Logged in'
     else
        flash[:alert] = "Wrong email or password"
        render :new
     end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :find_user, only: [:update,:pass_update]

    def new
        @user = User.new
    end

    def create 
        @user = User.new user_params
        if @user.save
            redirect_to root_path
        else
            render :new
        end
    end

    def edit
        @user = current_user
        # params[:id] == @user.id
    end

    def update
        if current_user.update user_params
            redirect_to root_path
        else
            render :edit
        end
    end

   
    def pass_edit
        @user = current_user
    end

    def pass_update
        # if current_user&.authenticate(params[:current_password])
        if current_user&.authenticate pass_params
            if params[:current_user] != current_user.password
                render edit_user_password_path, alert: "invalid password"
            
            elsif params[:new_password] == params[:current_user]
                render edit_user_password_path, alert: "new password can't be same as current password"
            elsif params[:new_password] != params[:password_confirmation]
                render edit_user_password_path, alert: "password confirmaion is wrong"
            else password.update 
                current_user.password == params[:new_password]
                render edit_user_path(current_user)
        
             end
            end
       
    end

    private

    def find_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def pass_params
        params.require(:user).permit(:name, :email, :current_password, :new_password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogOnRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-sm navbar-light bg-light">
  <div class="navbar-brand">
  <%= link_to 'Blog_on_rails', root_path %></div>

  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <ul class="navbar-nav ml-auto">
    <li><%= link_to 'Home', root_path %></li>
    <% if current_user %>
    <li><%= link_to current_user.name, edit_user_path(current_user) %></li>
    <li><%= link_to 'New Post', new_post_path %></li>
    <li><%= link_to 'Sign Out', session_path, method: :delete, data: {confirm: "are you sure you want to log"} %></li>
    <% else %>
    <li><%= link_to 'Sign Up', new_user_path %></li>
    <li><%= link_to 'Sign In', new_session_path %></li>
    <% end %>
    </ul>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="container-fluid padding">
  <div class="form">
      <%= form_with(model: @post, local: true) do |form| %>
      <% if @post.errors.present? %>
        <p class="form-errors">
          <%= @post.errors.full_messages.join(", ") %>
        </p>
      <% end %>
      <div class="form-group">
        <%= form.label :title %> <br>
        <%= form.text_field :title, class:"form-control"%>
      </div>
      <div class="form-group">
        <%= form.label :body %> <br>
        <%= form.text_area :body, class:"form-control"%>
      </div>
      <%= form.submit class:"btn btn-outline-primary" %>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form" %>

app/views/posts/index.html.erb
<div class="container-fluid">
<% if flash[:alert] %>
  <p><%= flash[:alert] %></p>
<% end %>
    <div class="row">
        <% @posts.take(15).each do | post|%>
            <div class="row col-md-6 col-lg-4 mx-auto">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">
                            <%= link_to(post.title, post_path(post))%>
                        </h4>
                        <p class="card-text"><%= post.body.first(50) %>...
                        </p>
                    </div>   
                </div>
            </div>  
        <% end %>
    </div>
</div>

app/views/posts/new.html.erb
<%= render "form" %>

app/views/posts/show.html.erb
<div class="container-fluid padding">
<h3><%= @post.title %></h3>

<p class="lead"><%= @post.body %></p>
<h4>
  Created by: <%= @post.user&.name || 'DELETED' %>
</h4>

<small>
Posted <%= time_ago_in_words(@post.created_at) %> ago
</small>

<div>
    <button class="btn btn-outline-primary edit-btn my-2">
    <small>
        <%= link_to "Edit", edit_post_path(@post) %>
    </small> 
    </button>
    <button class="btn btn-outline-primary delete-btn my-2">
    <small>
        <%= link_to "Delete", post_path(@post),method: :delete, data: {confirm: "Are you sure?"} %>
    </small> 
    </button>
</div>

<section>
  <h4>Comments</h4>

  <%= form_with(model: [@post, @comment], local: true) do |f| %>
    <% if @comment.errors.present? %>
      <p class="form-errors">
        <%= @comment.errors.full_messages.join(", ") %>
      </p>
    <% end %>


    <div class="form-group">
      <%= f.text_area(
      :body, cols: 50, rows: 5,
      placeholder: "What'on your mind?",
      class: "form-control"
      ) %>
    </div>
    <%= f.submit "Comment", class:"btn btn-outline-primary" %>
  <% end %>

  <hr />


      <% @comments.each do |comment| %>
          <p>
          <%= comment.body %> <br />
          <small>
            <%= link_to(
            "Delete",
            post_comment_path(@post, comment),
            method: :delete, data: {
              confirm: "Are you sure?"
            }
            ) %>
          </small>
          <small>
            Commented <%= time_ago_in_words(comment.created_at) %> ago
          </small>
            <small>
              commented by: <%= comment.user&.name || 'DELETED' %>
          </small>
        </p>
   
      <% end %>
  
</section>

</div>

app/views/users/edit.html.erb
<div class="container-fluid padding">
  <div class="form">
      <%= form_with(model: @user, local: true) do |form| %>
      <% if @user.errors.present? %>
        <p class="form-errors">
          <%= @user.errors.full_messages.join(", ") %>
        </p>
      <% end %>
      <div class="form-group">
        <%= form.label :name %> <br>
        <%= form.text_field :name, class:"form-control"%>
      </div>
      <div class="form-group">
        <%= form.label :email %> <br>
        <%= form.email_field :email, class:"form-control"%>
      </div>
      <%= form.submit class:"btn btn-outline-primary" %>
      <button class="btn btn-outline-primary">
        <%= link_to "Change Password", edit_user_password_path %>
      </button>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_with model: @user, local: true do |f| %>
  <% if @user.errors.any? %>
    <p>
      <%= @user.errors.full_messages.join(', ') %>
    </p>
  <% end %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit "Sign Up" %>
<% end %>

app/views/users/pass_edit.html.erb
<div class="container-fluid padding">
  <div class="form">
      <%= form_with(model: @user, local: true) do |form| %>
      <% if @user.errors.present? %>
        <p class="form-errors">
          <%= @user.errors.full_messages.join(", ") %>
        </p>
      <% end %>
      <div class="form-group">
        <%= form.label :current_password %> <br>
        <%= form.password_field :current_password, class:"form-control"%>
      </div>
      <div class="form-group">
        <%= form.label :new_password %> <br>
        <%= form.password_field :new_password, class:"form-control"%>
      </div>
      <div class="form-group">
        <%= form.label :password_confirmation %> <br>
        <%= form.password_field :password_confirmation, class:"form-control"%>
      </div>
      <%= form.submit "Update", class:"btn btn-outline-primary" %>
    <% end %>
  </div>
</div>